export type IVec3 = readonly [number, number, number]
/** Row-major 3x3 matrix. */
export type IMat3 = readonly [IVec3, IVec3, IVec3]

export const IDENTITY: IMat3 = [
  [1, 0, 0],
  [0, 1, 0],
  [0, 0, 1],
]

export function add(a: IVec3, b: IVec3): IVec3 {
  return [a[0] + b[0], a[1] + b[1], a[2] + b[2]]
}

export function sub(a: IVec3, b: IVec3): IVec3 {
  return [a[0] - b[0], a[1] - b[1], a[2] - b[2]]
}

export function apply(m: IMat3, v: IVec3): IVec3 {
  return [
    m[0][0] * v[0] + m[0][1] * v[1] + m[0][2] * v[2],
    m[1][0] * v[0] + m[1][1] * v[1] + m[1][2] * v[2],
    m[2][0] * v[0] + m[2][1] * v[1] + m[2][2] * v[2],
  ]
}

/** Matrix product a*b (apply(mul(a,b), v) === apply(a, apply(b, v))). */
export function mul(a: IMat3, b: IMat3): IMat3 {
  const rows: IVec3[] = []
  for (let i = 0; i < 3; i++) {
    const row: number[] = []
    for (let j = 0; j < 3; j++) {
      let sum = 0
      for (let k = 0; k < 3; k++) {
        // biome-ignore lint: bounded 3x3 loop
        sum += a[i]![k]! * b[k]![j]!
      }
      row.push(sum)
    }
    rows.push(row as unknown as IVec3)
  }
  return rows as unknown as IMat3
}

/** Inverse of an orthogonal (rotation) matrix is its transpose. */
export function transpose(m: IMat3): IMat3 {
  return [
    [m[0][0], m[1][0], m[2][0]],
    [m[0][1], m[1][1], m[2][1]],
    [m[0][2], m[1][2], m[2][2]],
  ]
}

export function equalMat(a: IMat3, b: IMat3): boolean {
  for (let i = 0; i < 3; i++) {
    for (let j = 0; j < 3; j++) {
      // biome-ignore lint: bounded 3x3 loop
      if (a[i]![j] !== b[i]![j]) return false
    }
  }
  return true
}

export function determinant(m: IMat3): number {
  const [[a, b, c], [d, e, f], [g, h, i]] = m
  return a * (e * i - f * h) - b * (d * i - f * g) + c * (d * h - e * g)
}

function matKey(m: IMat3): string {
  return m.flat().join(',')
}

/** Rotation by +90 degrees about the X-axis direction (mixes Y,Z; X fixed). */
const RX_POS_90: IMat3 = [
  [1, 0, 0],
  [0, 0, -1],
  [0, 1, 0],
]
/** Rotation by -90 degrees about the X-axis direction. */
const RX_NEG_90: IMat3 = transpose(RX_POS_90)
/** Rotation by +90 degrees about the Y-axis direction (mixes X,Z; Y fixed). */
const RY_POS_90: IMat3 = [
  [0, 0, 1],
  [0, 1, 0],
  [-1, 0, 0],
]
/** Rotation by -90 degrees about the Y-axis direction. */
const RY_NEG_90: IMat3 = transpose(RY_POS_90)

export const AXIS_ROTATIONS = {
  x: { 1: RX_POS_90, [-1]: RX_NEG_90 } as Record<1 | -1, IMat3>,
  y: { 1: RY_POS_90, [-1]: RY_NEG_90 } as Record<1 | -1, IMat3>,
}

/** Generated by closure of the two 90-degree generators — the 24-element proper rotation group of the cube. */
export const ROTATIONS_24: readonly IMat3[] = (() => {
  const seen = new Map<string, IMat3>()
  seen.set(matKey(IDENTITY), IDENTITY)
  const queue: IMat3[] = [IDENTITY]
  const generators = [RX_POS_90, RY_POS_90]
  while (queue.length > 0) {
    const m = queue.shift() as IMat3
    for (const g of generators) {
      const next = mul(g, m)
      const k = matKey(next)
      if (!seen.has(k)) {
        seen.set(k, next)
        queue.push(next)
      }
    }
  }
  return Array.from(seen.values())
})()

export interface ScrewMotion {
  rotation: IMat3
  translation: IVec3
}

/** A pure rotation about an axis-direction line passing through `pivot`, expressed as an affine (screw) motion. */
export function hingeRotation(axis: 'x' | 'y', pivot: IVec3, sign: 1 | -1): ScrewMotion {
  const rotation = AXIS_ROTATIONS[axis][sign]
  // p' = R*(p - pivot) + pivot = R*p + (pivot - R*pivot)
  const translation = sub(pivot, apply(rotation, pivot))
  return { rotation, translation }
}

export function applyScrew(s: ScrewMotion, p: IVec3): IVec3 {
  return add(apply(s.rotation, p), s.translation)
}

/** Compose two screw motions: apply `inner` first (in `outer`'s local frame), then `outer`. */
export function composeScrew(outer: ScrewMotion, inner: ScrewMotion): ScrewMotion {
  return {
    rotation: mul(outer.rotation, inner.rotation),
    translation: add(apply(outer.rotation, inner.translation), outer.translation),
  }
}
